text = '''
6 STEPS TO SELECTING A FIELD SERVICE SOLUTION
1.  WHAT ARE YOUR GOALS AND OBJECTIVES AS A BUSINESS?
2.  WHAT DO YOU REALLY NEED FROM A SOLUTION?
3.  FEATURES OF THE SOLUTION:
4.  NON-FUNCTIONAL REQUIREMENTS:
5.  COMPARING APPLES TO APPLES:
6.  GIVE THE SYSTEM A TEST RUN:
'''

print(text.lower())
